### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by ox7** [ox7/lymph#1]
os version : 4.1.2
device : HUAWEI A199

> E/AndroidRuntime(12423): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.elong.mobile.basemantis/com.elong.mobile.plugin.baseactivity}: java.lang.ClassCastException: com.elong.mobile.plugin.hr.EPluginContextWrapper cannot be cast to android.app.Application
E/AndroidRuntime(12423): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2069)
E/AndroidRuntime(12423): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2094)
E/AndroidRuntime(12423): 	at android.app.ActivityThread.access$600(ActivityThread.java:134)
E/AndroidRuntime(12423): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
E/AndroidRuntime(12423): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12423): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(12423): 	at android.app.ActivityThread.main(ActivityThread.java:4791)
E/AndroidRuntime(12423): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12423): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(12423): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:766)
E/AndroidRuntime(12423): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:533)
E/AndroidRuntime(12423): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(12423): Caused by: java.lang.ClassCastException: com.elong.mobile.plugin.hr.EPluginContextWrapper cannot be cast to android.app.Application
E/AndroidRuntime(12423): 	at android.view.Window.getCompatInfo(Window.java:481)
E/AndroidRuntime(12423): 	at android.view.Window$LocalWindowManager.<init>(Window.java:491)
E/AndroidRuntime(12423): 	at android.view.Window.setWindowManager(Window.java:477)
E/AndroidRuntime(12423): 	at android.app.Activity.attach(Activity.java:5015)
E/AndroidRuntime(12423): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2018)
E/AndroidRuntime(12423): 	... 11 more
W/ActivityManager(  343):   Force finishing activity com.elong.mobile.basemantis/com.elong.mobile.plugin.baseactivity

**Comment by ox7** [comment]
> EPluginContextWrapper -> 	

	@Override
	public Context getApplicationContext() {
		Log.i(TAG, "getApplicationContext()");
                //return this //is error.
		return plugin.getApplication();
	}
